// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POSystem.Entities;

internal partial class Vendor
{
    [Key]
    public int VendorID { get; set; }

    [Required]
    [StringLength(100)]
    public string VendorName { get; set; }

    [Required]
    [StringLength(12)]
    public string Phone { get; set; }

    [Required]
    [StringLength(30)]
    public string Address { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string City { get; set; }

    [Required]
    [StringLength(2)]
    public string ProvinceID { get; set; }

    [Required]
    [StringLength(6)]
    public string PostalCode { get; set; }

    public bool RemoveFromViewFlag { get; set; }

    [InverseProperty("Vendor")]
    public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; } = new List<PurchaseOrder>();

    [InverseProperty("Vendor")]
    public virtual ICollection<StockItem> StockItems { get; set; } = new List<StockItem>();
}