// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RMSSystem.Entities;

[Index("OfferingSectionID", Name = "IX_OfferingSectionID")]
[Index("StudentNumber", Name = "IX_StudentNumber")]
internal partial class ClassMember
{
    [Key]
    public int RegistrationID { get; set; }

    public int StudentNumber { get; set; }

    public int OfferingSectionID { get; set; }

    public int? Mark { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? WithdrawalDate { get; set; }

    public bool IsAuditing { get; set; }

    public bool RemoveFromViewFlag { get; set; }

    [InverseProperty("Registration")]
    public virtual ICollection<GradeAssignment> GradeAssignments { get; set; } = new List<GradeAssignment>();

    [ForeignKey("OfferingSectionID")]
    [InverseProperty("ClassMembers")]
    public virtual ClassOffering OfferingSection { get; set; }

    [ForeignKey("StudentNumber")]
    [InverseProperty("ClassMembers")]
    public virtual Student StudentNumberNavigation { get; set; }
}