// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RMSSystem.Entities;

[Index("RentalID", Name = "IX_RentalID")]
[Index("StudentNumber", Name = "IX_StudentNumber")]
internal partial class Renter
{
    [Key]
    public int RenterID { get; set; }

    public int StudentNumber { get; set; }

    public int RentalID { get; set; }

    [Column(TypeName = "date")]
    public DateTime EffectiveDate { get; set; }

    public bool Active { get; set; }

    [StringLength(50)]
    public string EmergencyContactName { get; set; }

    [StringLength(12)]
    [Unicode(false)]
    public string EmergencyContactNumber { get; set; }

    public bool RemoveFromViewFlag { get; set; }

    [ForeignKey("RentalID")]
    [InverseProperty("Renters")]
    public virtual Rental Rental { get; set; }

    [ForeignKey("StudentNumber")]
    [InverseProperty("Renters")]
    public virtual Student StudentNumberNavigation { get; set; }
}