// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SalesSystem.Entities;

internal partial class SaleRefundDetail
{
    [Key]
    public int SaleRefundDetailID { get; set; }

    public int SaleRefundID { get; set; }

    public int StockItemID { get; set; }

    [Column(TypeName = "money")]
    public decimal SellingPrice { get; set; }

    public int Quantity { get; set; }

    public bool RemoveFromViewFlag { get; set; }

    [ForeignKey("SaleRefundID")]
    [InverseProperty("SaleRefundDetails")]
    public virtual SaleRefund SaleRefund { get; set; }

    [ForeignKey("StockItemID")]
    [InverseProperty("SaleRefundDetails")]
    public virtual StockItem StockItem { get; set; }
}