// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POSystem.Entities;

[Table("StockItems")]
internal partial class StockItem
{
    [Key]
    public int StockItemID { get; set; }

    [Required]
    [StringLength(50)]
    public string Description { get; set; }

    [Column(TypeName = "smallmoney")]
    public decimal SellingPrice { get; set; }

    [Column(TypeName = "smallmoney")]
    public decimal PurchasePrice { get; set; }

    public int QuantityOnHand { get; set; }

    public int QuantityOnOrder { get; set; }

    public int ReOrderLevel { get; set; }

    public bool Discontinued { get; set; }

    public int VendorID { get; set; }

    [StringLength(25)]
    public string VendorStockNumber { get; set; }

    public int CategoryID { get; set; }

    public bool RemoveFromViewFlag { get; set; }

    [InverseProperty("StockItem")]
    public virtual ICollection<PurchaseOrderDetail> PurchaseOrderDetails { get; set; } = new List<PurchaseOrderDetail>();

    [ForeignKey("VendorID")]
    [InverseProperty("StockItems")]
    public virtual Vendor Vendor { get; set; }
}