// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RMSSystem.Entities;

internal partial class AssessmentType
{
    [Key]
    public int AssessmentTypeID { get; set; }

    [Required]
    [StringLength(30)]
    public string Name { get; set; }

    public bool RemoveFromViewFlag { get; set; }

    [InverseProperty("AssessmentType")]
    public virtual ICollection<PlannedAssessment> PlannedAssessments { get; set; } = new List<PlannedAssessment>();
}