// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RMSSystem.Entities;

[Index("OfferingID", Name = "IX_OfferingID")]
internal partial class Assignment
{
    [Key]
    public int AssignmentID { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string Name { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Description { get; set; }

    public int OfferingID { get; set; }

    public short PossibleMarks { get; set; }

    public short? ExtraBonusMarks { get; set; }

    public short Weight { get; set; }

    public bool RemoveFromViewFlag { get; set; }

    [InverseProperty("Assignment")]
    public virtual ICollection<GradeAssignment> GradeAssignments { get; set; } = new List<GradeAssignment>();

    [ForeignKey("OfferingID")]
    [InverseProperty("Assignments")]
    public virtual Offering Offering { get; set; }
}