// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RMSSystem.Entities;

[Index("EmployeeID", Name = "IX_EmployeeID")]
internal partial class Club
{
    [Key]
    [StringLength(10)]
    [Unicode(false)]
    public string ClubID { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string ClubName { get; set; }

    public bool Active { get; set; }

    public int? EmployeeID { get; set; }

    [Column(TypeName = "money")]
    public decimal Fee { get; set; }

    public bool RemoveFromViewFlag { get; set; }

    [InverseProperty("Club")]
    public virtual ICollection<ClubActivity> ClubActivities { get; set; } = new List<ClubActivity>();

    [InverseProperty("Club")]
    public virtual ICollection<ClubMember> ClubMembers { get; set; } = new List<ClubMember>();

    [ForeignKey("EmployeeID")]
    [InverseProperty("Clubs")]
    public virtual Employee Employee { get; set; }
}