// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RMSSystem.Entities;

[Index("CourseID", Name = "IX_CourseID")]
[Index("ProgramID", Name = "IX_ProgramID")]
[Index("ProgramID", "CourseID", Name = "UN_dbo.ProgramCourses_ProgramIDCourseID", IsUnique = true)]
internal partial class ProgramCourse
{
    [Key]
    public int ProgramCourseID { get; set; }

    public int ProgramID { get; set; }

    [Required]
    [StringLength(7)]
    [Unicode(false)]
    public string CourseID { get; set; }

    public bool Required { get; set; }

    [StringLength(50)]
    public string Comments { get; set; }

    public int SectionLimit { get; set; }

    public bool Active { get; set; }

    public bool RemoveFromViewFlag { get; set; }

    [ForeignKey("CourseID")]
    [InverseProperty("ProgramCourses")]
    public virtual Course Course { get; set; }

    [InverseProperty("ProgramCourse")]
    public virtual ICollection<Offering> Offerings { get; set; } = new List<Offering>();

    [ForeignKey("ProgramID")]
    [InverseProperty("ProgramCourses")]
    public virtual Program Program { get; set; }
}