// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RMSSystem.Entities;

[Index("AddressID", Name = "IX_AddressID")]
[Index("ForwardingAddressID", Name = "IX_ForwardingAddressID")]
[Index("StudentID", Name = "IX_StudentID")]
internal partial class StudentAddress
{
    [Key]
    public int StudentAddressID { get; set; }

    public int StudentID { get; set; }

    public int AddressID { get; set; }

    [Column(TypeName = "date")]
    public DateTime SinceDate { get; set; }

    [Column(TypeName = "date")]
    public DateTime? UntilDate { get; set; }

    public int? ForwardingAddressID { get; set; }

    public bool IsPrimaryResidence { get; set; }

    public bool RemoveFromViewFlag { get; set; }

    [ForeignKey("AddressID")]
    [InverseProperty("StudentAddressAddresses")]
    public virtual Address Address { get; set; }

    [ForeignKey("ForwardingAddressID")]
    [InverseProperty("StudentAddressForwardingAddresses")]
    public virtual Address ForwardingAddress { get; set; }

    [ForeignKey("StudentID")]
    [InverseProperty("StudentAddresses")]
    public virtual Student Student { get; set; }
}