// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RMSSystem.Entities;

internal partial class Address
{
    [Key]
    public int AddressID { get; set; }

    [Required]
    [StringLength(30)]
    [Unicode(false)]
    public string Number { get; set; }

    [Required]
    [StringLength(30)]
    [Unicode(false)]
    public string Street { get; set; }

    [StringLength(30)]
    [Unicode(false)]
    public string Community { get; set; }

    [StringLength(5)]
    [Unicode(false)]
    public string Unit { get; set; }

    [Required]
    [StringLength(30)]
    [Unicode(false)]
    public string City { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string ProvinceState { get; set; }

    [StringLength(12)]
    [Unicode(false)]
    public string PostalCodeZip { get; set; }

    [StringLength(2)]
    [Unicode(false)]
    public string CountryCode { get; set; }

    public int? LandLordID { get; set; }

    public bool RemoveFromViewFlag { get; set; }

    [ForeignKey("LandLordID")]
    [InverseProperty("Addresses")]
    public virtual PropertyOwner LandLord { get; set; }

    [InverseProperty("Address")]
    public virtual ICollection<Rental> Rentals { get; set; } = new List<Rental>();

    [InverseProperty("Address")]
    public virtual ICollection<StudentAddress> StudentAddressAddresses { get; set; } = new List<StudentAddress>();

    [InverseProperty("ForwardingAddress")]
    public virtual ICollection<StudentAddress> StudentAddressForwardingAddresses { get; set; } = new List<StudentAddress>();
}