// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RMSSystem.Entities;

[Index("SchoolCode", Name = "IX_SchoolCode")]
internal partial class Program
{
    [Key]
    public int ProgramID { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string ProgramName { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string DiplomaName { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string SchoolCode { get; set; }

    [Column(TypeName = "money")]
    public decimal Tuition { get; set; }

    [Column(TypeName = "money")]
    public decimal InternationalTuition { get; set; }

    public bool RemoveFromViewFlag { get; set; }

    [InverseProperty("Program")]
    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();

    [InverseProperty("Program")]
    public virtual ICollection<ProgramCourse> ProgramCourses { get; set; } = new List<ProgramCourse>();

    [ForeignKey("SchoolCode")]
    [InverseProperty("Programs")]
    public virtual School SchoolCodeNavigation { get; set; }
}