// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RMSSystem.Entities;

internal partial class PropertyOwner
{
    [Key]
    public int LandlordID { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Name { get; set; }

    [Required]
    [StringLength(12)]
    [Unicode(false)]
    public string ContactNumber { get; set; }

    public bool ActiveContract { get; set; }

    public bool RemoveFromViewFlag { get; set; }

    [InverseProperty("LandLord")]
    public virtual ICollection<Address> Addresses { get; set; } = new List<Address>();
}