// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RMSSystem.Entities;

[Index("RoleID", Name = "IX_RoleID")]
internal partial class Role
{
    [Key]
    public int RoleID { get; set; }

    [Required]
    [StringLength(20)]
    public string Description { get; set; }

    public bool RemoveFromViewFlag { get; set; }

    [InverseProperty("Role")]
    public virtual ICollection<ClubMember> ClubMembers { get; set; } = new List<ClubMember>();
}