// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RMSSystem.Entities;

internal partial class School
{
    [Key]
    [StringLength(10)]
    [Unicode(false)]
    public string SchoolCode { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string SchoolName { get; set; }

    public bool RemoveFromViewFlag { get; set; }

    [InverseProperty("SchoolCodeNavigation")]
    public virtual ICollection<Program> Programs { get; set; } = new List<Program>();
}