// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RMSSystem.Entities;

[Index("StudentNumber", Name = "IX_StudentNumber")]
internal partial class StudentPayment
{
    [Key]
    public int PaymentNumber { get; set; }

    public int StudentNumber { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? PaymentDate { get; set; }

    [Column(TypeName = "money")]
    public decimal Amount { get; set; }

    public bool Refunded { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? RefundDate { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Description { get; set; }

    public bool RemoveFromViewFlag { get; set; }

    [ForeignKey("StudentNumber")]
    [InverseProperty("StudentPayments")]
    public virtual Student StudentNumberNavigation { get; set; }
}