// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SalesSystem.Entities;

internal partial class SaleDetail
{
    [Key]
    public int SaleDetailID { get; set; }

    public int SaleID { get; set; }

    public int StockItemID { get; set; }

    [Column(TypeName = "smallmoney")]
    public decimal SellingPrice { get; set; }

    public int Quantity { get; set; }

    public bool RemoveFromViewFlag { get; set; }

    [ForeignKey("SaleID")]
    [InverseProperty("SaleDetails")]
    public virtual Sale Sale { get; set; }

    [ForeignKey("StockItemID")]
    [InverseProperty("SaleDetails")]
    public virtual StockItem StockItem { get; set; }
}